
# This file is automatically generated, you probably don't want to edit this

IndttestOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "IndttestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            varEq = FALSE,
            iters = 3500,
            chain = 4,
            warmup = 1000,
            core = 2,
            seed = 401,
            CI = TRUE,
            Range.CI = 95,
            HPDI = FALSE,
            Range.HPDI = 95,
            check_Rhat = FALSE,
            check_ac = FALSE,
            check_trace = FALSE,
            mean_diff = FALSE,
            mean_diff_Range = 95,
            mean_diff_over = FALSE,
            mean_diff_over_c = 0,
            ES = FALSE,
            ES_Range = 95,
            ES_over = FALSE,
            ES_over_c = 0,
            U3 = FALSE,
            Range_U3 = 95,
            U3_over = FALSE,
            U3_over_x = 0,
            pi_d = FALSE,
            Range_pi_d = 95,
            pi_d_over = FALSE,
            pi_d_over_x = 0,
            pi_c = FALSE,
            pi_c_c = 0,
            Range_pi_c = 95,
            pi_c_over = FALSE,
            pi_c_over_x = 0, ...) {

            super$initialize(
                package='jmvstan',
                name='Indttest',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..varEq <- jmvcore::OptionBool$new(
                "varEq",
                varEq,
                default=FALSE)
            private$..iters <- jmvcore::OptionInteger$new(
                "iters",
                iters,
                min=0,
                max=100000000,
                default=3500)
            private$..chain <- jmvcore::OptionInteger$new(
                "chain",
                chain,
                min=1,
                max=100000000,
                default=4)
            private$..warmup <- jmvcore::OptionInteger$new(
                "warmup",
                warmup,
                min=1,
                max=100000000,
                default=1000)
            private$..core <- jmvcore::OptionInteger$new(
                "core",
                core,
                min=1,
                max=100000000,
                default=2)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                max=100000000,
                default=401)
            private$..CI <- jmvcore::OptionBool$new(
                "CI",
                CI,
                default=TRUE)
            private$..Range.CI <- jmvcore::OptionNumber$new(
                "Range.CI",
                Range.CI,
                min=0.001,
                max=99.999,
                default=95)
            private$..HPDI <- jmvcore::OptionBool$new(
                "HPDI",
                HPDI,
                default=FALSE)
            private$..Range.HPDI <- jmvcore::OptionNumber$new(
                "Range.HPDI",
                Range.HPDI,
                min=0.001,
                max=99.999,
                default=95)
            private$..check_Rhat <- jmvcore::OptionBool$new(
                "check_Rhat",
                check_Rhat,
                default=FALSE)
            private$..check_ac <- jmvcore::OptionBool$new(
                "check_ac",
                check_ac,
                default=FALSE)
            private$..check_trace <- jmvcore::OptionBool$new(
                "check_trace",
                check_trace,
                default=FALSE)
            private$..mean_diff <- jmvcore::OptionBool$new(
                "mean_diff",
                mean_diff,
                default=FALSE)
            private$..mean_diff_Range <- jmvcore::OptionNumber$new(
                "mean_diff_Range",
                mean_diff_Range,
                min=0.001,
                max=99.999,
                default=95)
            private$..mean_diff_over <- jmvcore::OptionBool$new(
                "mean_diff_over",
                mean_diff_over,
                default=FALSE)
            private$..mean_diff_over_c <- jmvcore::OptionNumber$new(
                "mean_diff_over_c",
                mean_diff_over_c,
                min=-100000000,
                max=100000000,
                default=0)
            private$..ES <- jmvcore::OptionBool$new(
                "ES",
                ES,
                default=FALSE)
            private$..ES_Range <- jmvcore::OptionNumber$new(
                "ES_Range",
                ES_Range,
                min=0.001,
                max=99.999,
                default=95)
            private$..ES_over <- jmvcore::OptionBool$new(
                "ES_over",
                ES_over,
                default=FALSE)
            private$..ES_over_c <- jmvcore::OptionNumber$new(
                "ES_over_c",
                ES_over_c,
                min=-100000000,
                max=100000000,
                default=0)
            private$..U3 <- jmvcore::OptionBool$new(
                "U3",
                U3,
                default=FALSE)
            private$..Range_U3 <- jmvcore::OptionNumber$new(
                "Range_U3",
                Range_U3,
                min=0.001,
                max=99.999,
                default=95)
            private$..U3_over <- jmvcore::OptionBool$new(
                "U3_over",
                U3_over,
                default=FALSE)
            private$..U3_over_x <- jmvcore::OptionNumber$new(
                "U3_over_x",
                U3_over_x,
                min=-100000000,
                max=100000000,
                default=0)
            private$..pi_d <- jmvcore::OptionBool$new(
                "pi_d",
                pi_d,
                default=FALSE)
            private$..Range_pi_d <- jmvcore::OptionNumber$new(
                "Range_pi_d",
                Range_pi_d,
                min=0.001,
                max=99.999,
                default=95)
            private$..pi_d_over <- jmvcore::OptionBool$new(
                "pi_d_over",
                pi_d_over,
                default=FALSE)
            private$..pi_d_over_x <- jmvcore::OptionNumber$new(
                "pi_d_over_x",
                pi_d_over_x,
                min=-100000000,
                max=100000000,
                default=0)
            private$..pi_c <- jmvcore::OptionBool$new(
                "pi_c",
                pi_c,
                default=FALSE)
            private$..pi_c_c <- jmvcore::OptionNumber$new(
                "pi_c_c",
                pi_c_c,
                min=-100000000,
                max=100000000,
                default=0)
            private$..Range_pi_c <- jmvcore::OptionNumber$new(
                "Range_pi_c",
                Range_pi_c,
                min=0.001,
                max=99.999,
                default=95)
            private$..pi_c_over <- jmvcore::OptionBool$new(
                "pi_c_over",
                pi_c_over,
                default=FALSE)
            private$..pi_c_over_x <- jmvcore::OptionNumber$new(
                "pi_c_over_x",
                pi_c_over_x,
                min=-100000000,
                max=100000000,
                default=0)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..varEq)
            self$.addOption(private$..iters)
            self$.addOption(private$..chain)
            self$.addOption(private$..warmup)
            self$.addOption(private$..core)
            self$.addOption(private$..seed)
            self$.addOption(private$..CI)
            self$.addOption(private$..Range.CI)
            self$.addOption(private$..HPDI)
            self$.addOption(private$..Range.HPDI)
            self$.addOption(private$..check_Rhat)
            self$.addOption(private$..check_ac)
            self$.addOption(private$..check_trace)
            self$.addOption(private$..mean_diff)
            self$.addOption(private$..mean_diff_Range)
            self$.addOption(private$..mean_diff_over)
            self$.addOption(private$..mean_diff_over_c)
            self$.addOption(private$..ES)
            self$.addOption(private$..ES_Range)
            self$.addOption(private$..ES_over)
            self$.addOption(private$..ES_over_c)
            self$.addOption(private$..U3)
            self$.addOption(private$..Range_U3)
            self$.addOption(private$..U3_over)
            self$.addOption(private$..U3_over_x)
            self$.addOption(private$..pi_d)
            self$.addOption(private$..Range_pi_d)
            self$.addOption(private$..pi_d_over)
            self$.addOption(private$..pi_d_over_x)
            self$.addOption(private$..pi_c)
            self$.addOption(private$..pi_c_c)
            self$.addOption(private$..Range_pi_c)
            self$.addOption(private$..pi_c_over)
            self$.addOption(private$..pi_c_over_x)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        varEq = function() private$..varEq$value,
        iters = function() private$..iters$value,
        chain = function() private$..chain$value,
        warmup = function() private$..warmup$value,
        core = function() private$..core$value,
        seed = function() private$..seed$value,
        CI = function() private$..CI$value,
        Range.CI = function() private$..Range.CI$value,
        HPDI = function() private$..HPDI$value,
        Range.HPDI = function() private$..Range.HPDI$value,
        check_Rhat = function() private$..check_Rhat$value,
        check_ac = function() private$..check_ac$value,
        check_trace = function() private$..check_trace$value,
        mean_diff = function() private$..mean_diff$value,
        mean_diff_Range = function() private$..mean_diff_Range$value,
        mean_diff_over = function() private$..mean_diff_over$value,
        mean_diff_over_c = function() private$..mean_diff_over_c$value,
        ES = function() private$..ES$value,
        ES_Range = function() private$..ES_Range$value,
        ES_over = function() private$..ES_over$value,
        ES_over_c = function() private$..ES_over_c$value,
        U3 = function() private$..U3$value,
        Range_U3 = function() private$..Range_U3$value,
        U3_over = function() private$..U3_over$value,
        U3_over_x = function() private$..U3_over_x$value,
        pi_d = function() private$..pi_d$value,
        Range_pi_d = function() private$..Range_pi_d$value,
        pi_d_over = function() private$..pi_d_over$value,
        pi_d_over_x = function() private$..pi_d_over_x$value,
        pi_c = function() private$..pi_c$value,
        pi_c_c = function() private$..pi_c_c$value,
        Range_pi_c = function() private$..Range_pi_c$value,
        pi_c_over = function() private$..pi_c_over$value,
        pi_c_over_x = function() private$..pi_c_over_x$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..varEq = NA,
        ..iters = NA,
        ..chain = NA,
        ..warmup = NA,
        ..core = NA,
        ..seed = NA,
        ..CI = NA,
        ..Range.CI = NA,
        ..HPDI = NA,
        ..Range.HPDI = NA,
        ..check_Rhat = NA,
        ..check_ac = NA,
        ..check_trace = NA,
        ..mean_diff = NA,
        ..mean_diff_Range = NA,
        ..mean_diff_over = NA,
        ..mean_diff_over_c = NA,
        ..ES = NA,
        ..ES_Range = NA,
        ..ES_over = NA,
        ..ES_over_c = NA,
        ..U3 = NA,
        ..Range_U3 = NA,
        ..U3_over = NA,
        ..U3_over_x = NA,
        ..pi_d = NA,
        ..Range_pi_d = NA,
        ..pi_d_over = NA,
        ..pi_d_over_x = NA,
        ..pi_c = NA,
        ..pi_c_c = NA,
        ..Range_pi_c = NA,
        ..pi_c_over = NA,
        ..pi_c_over_x = NA)
)

IndttestResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        triggertable = function() private$.items[["triggertable"]],
        maintable = function() private$.items[["maintable"]],
        rhatplot = function() private$.items[["rhatplot"]],
        acplot = function() private$.items[["acplot"]],
        traceplot = function() private$.items[["traceplot"]],
        EStable = function() private$.items[["EStable"]],
        PDanalysis = function() private$.items[["PDanalysis"]],
        PHCtable = function() private$.items[["PHCtable"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bayesian Independent Samples T-Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="triggertable",
                title="P",
                visible=FALSE,
                clearWith=list(
                    "dep",
                    "group",
                    "varEq",
                    "iters",
                    "chain",
                    "warmup",
                    "core",
                    "seed"),
                rows=1,
                columns=list(
                    list(
                        `name`="M", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="maintable",
                title="Posterior distribution(Independent Samples T-Test)",
                clearWith=list(
                    "dep",
                    "group",
                    "varEq",
                    "iters",
                    "chain",
                    "warmup",
                    "core",
                    "seed",
                    "Range.CI",
                    "Range.HPDI",
                    "varEq"),
                rows=4,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="MAP", 
                        `type`="number"),
                    list(
                        `name`="EAP", 
                        `type`="number"),
                    list(
                        `name`="MED", 
                        `type`="number"),
                    list(
                        `name`="CI.Lower", 
                        `title`="CI.Lower", 
                        `type`="number", 
                        `visible`="(CI)"),
                    list(
                        `name`="CI.Upper", 
                        `title`="CI.Upper", 
                        `type`="number", 
                        `visible`="(CI)"),
                    list(
                        `name`="HPDI.Lower", 
                        `title`="HDI.Lower", 
                        `type`="number", 
                        `visible`="(HPDI)"),
                    list(
                        `name`="HPDI.Upper", 
                        `title`="HDI.Upper", 
                        `type`="number", 
                        `visible`="(HPDI)"),
                    list(
                        `name`="Rhat", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="rhatplot",
                title="Rhat's Histogram",
                width=400,
                height=300,
                renderFun=".plotrhat",
                visible="(check_Rhat)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="acplot",
                title="Avg autocorrelation",
                width=400,
                height=300,
                renderFun=".plotac",
                visible="(check_ac)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="traceplot",
                title="Trace Plot",
                width=400,
                height=300,
                renderFun=".plottrace",
                visible="(check_trace)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="EStable",
                title="Effect size Posterior distribution",
                rows=0,
                visible="(mean_diff|ES)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="MAP", 
                        `type`="number"),
                    list(
                        `name`="EAP", 
                        `type`="number"),
                    list(
                        `name`="MED", 
                        `type`="number"),
                    list(
                        `name`="CI.Lower", 
                        `title`="CI.Lower", 
                        `type`="number"),
                    list(
                        `name`="CI.Upper", 
                        `title`="CI.Upper", 
                        `type`="number"),
                    list(
                        `name`="HPDI.Lower", 
                        `title`="HDI.Lower", 
                        `type`="number"),
                    list(
                        `name`="HPDI.Upper", 
                        `title`="HDI.Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="PDanalysis",
                title="Generated quantities analysis",
                rows=0,
                visible="(U3|pi_d|pi_c)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="MAP", 
                        `type`="number"),
                    list(
                        `name`="EAP", 
                        `type`="number"),
                    list(
                        `name`="MED", 
                        `type`="number"),
                    list(
                        `name`="CI.Lower", 
                        `title`="CI.Lower", 
                        `type`="number"),
                    list(
                        `name`="CI.Upper", 
                        `title`="CI.Upper", 
                        `type`="number"),
                    list(
                        `name`="HPDI.Lower", 
                        `title`="HDI.Lower", 
                        `type`="number"),
                    list(
                        `name`="HPDI.Upper", 
                        `title`="HDI.Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="PHCtable",
                title="Probability research hypothesis is true",
                rows=1,
                visible="(mean_diff_over|ES_over|U3_over|pi_d_over|pi_c_over)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="PHC", 
                        `type`="text"),
                    list(
                        `name`="mean_diff_o", 
                        `format`="zto,pvalue", 
                        `type`="number", 
                        `visible`="(mean_diff_over)"),
                    list(
                        `name`="ES_o", 
                        `format`="zto,pvalue", 
                        `type`="number", 
                        `visible`="(ES_over)"),
                    list(
                        `name`="U3_o", 
                        `format`="zto,pvalue", 
                        `type`="number", 
                        `visible`="(U3_over)"),
                    list(
                        `name`="pi_d_o", 
                        `format`="zto,pvalue", 
                        `type`="number", 
                        `visible`="(pi_d_over)"),
                    list(
                        `name`="pi_c_o", 
                        `format`="zto,pvalue", 
                        `type`="number", 
                        `visible`="(pi_c_over)"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Independent Samples T-Test",
                clearWith=list(
                    "dep",
                    "group",
                    "varEq",
                    "iters",
                    "chain",
                    "warmup",
                    "core",
                    "seed")))}))

IndttestBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "IndttestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jmvstan',
                name = 'Indttest',
                version = c(1,0,0),
                options = options,
                results = IndttestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bayesian Independent Samples T-Test
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param varEq .
#' @param iters .
#' @param chain .
#' @param warmup .
#' @param core .
#' @param seed .
#' @param CI .
#' @param Range.CI .
#' @param HPDI .
#' @param Range.HPDI .
#' @param check_Rhat .
#' @param check_ac .
#' @param check_trace .
#' @param mean_diff .
#' @param mean_diff_Range .
#' @param mean_diff_over .
#' @param mean_diff_over_c .
#' @param ES .
#' @param ES_Range .
#' @param ES_over .
#' @param ES_over_c .
#' @param U3 .
#' @param Range_U3 .
#' @param U3_over .
#' @param U3_over_x .
#' @param pi_d .
#' @param Range_pi_d .
#' @param pi_d_over .
#' @param pi_d_over_x .
#' @param pi_c .
#' @param pi_c_c .
#' @param Range_pi_c .
#' @param pi_c_over .
#' @param pi_c_over_x .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$triggertable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$maintable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rhatplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$acplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$traceplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$EStable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$PDanalysis} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$PHCtable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$triggertable$asDF}
#'
#' \code{as.data.frame(results$triggertable)}
#'
#' @export
Indttest <- function(
    data,
    dep,
    group,
    varEq = FALSE,
    iters = 3500,
    chain = 4,
    warmup = 1000,
    core = 2,
    seed = 401,
    CI = TRUE,
    Range.CI = 95,
    HPDI = FALSE,
    Range.HPDI = 95,
    check_Rhat = FALSE,
    check_ac = FALSE,
    check_trace = FALSE,
    mean_diff = FALSE,
    mean_diff_Range = 95,
    mean_diff_over = FALSE,
    mean_diff_over_c = 0,
    ES = FALSE,
    ES_Range = 95,
    ES_over = FALSE,
    ES_over_c = 0,
    U3 = FALSE,
    Range_U3 = 95,
    U3_over = FALSE,
    U3_over_x = 0,
    pi_d = FALSE,
    Range_pi_d = 95,
    pi_d_over = FALSE,
    pi_d_over_x = 0,
    pi_c = FALSE,
    pi_c_c = 0,
    Range_pi_c = 95,
    pi_c_over = FALSE,
    pi_c_over_x = 0) {

    if ( ! requireNamespace('jmvcore'))
        stop('Indttest requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))

    options <- IndttestOptions$new(
        dep = dep,
        group = group,
        varEq = varEq,
        iters = iters,
        chain = chain,
        warmup = warmup,
        core = core,
        seed = seed,
        CI = CI,
        Range.CI = Range.CI,
        HPDI = HPDI,
        Range.HPDI = Range.HPDI,
        check_Rhat = check_Rhat,
        check_ac = check_ac,
        check_trace = check_trace,
        mean_diff = mean_diff,
        mean_diff_Range = mean_diff_Range,
        mean_diff_over = mean_diff_over,
        mean_diff_over_c = mean_diff_over_c,
        ES = ES,
        ES_Range = ES_Range,
        ES_over = ES_over,
        ES_over_c = ES_over_c,
        U3 = U3,
        Range_U3 = Range_U3,
        U3_over = U3_over,
        U3_over_x = U3_over_x,
        pi_d = pi_d,
        Range_pi_d = Range_pi_d,
        pi_d_over = pi_d_over,
        pi_d_over_x = pi_d_over_x,
        pi_c = pi_c,
        pi_c_c = pi_c_c,
        Range_pi_c = Range_pi_c,
        pi_c_over = pi_c_over,
        pi_c_over_x = pi_c_over_x)

    results <- IndttestResults$new(
        options = options)

    analysis <- IndttestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
